language: java

env:
  - global:
      - M2_HOME=${HOME}/apache-maven-3.5.0 PATH=${M2_HOME}/bin:${PATH}

jdk:
  - oraclejdk8

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/apache-maven-3.5.0"

before_install:
  - if [ ! -d "${M2_HOME}"/bin ]; then curl https://archive.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz | tar zxf - -C "${HOME}"; fi

install:
  - mvn clean install -T 2.0C -DrepoToken=${repoToken} -Dmaven.javadoc.skip=true